---
machines:
  ok_web:
    hostname: "as_web"
    ipv4: "192.168.66.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/oakam-cms/"
      owner: www-data
      group: www-data
    port_map:
    - guest: 80
      host: 8080
    - guest: 443
      host: 4443

  ok_db:
    hostname: "as_db"
    ipv4: "192.168.66.20"
    playbook: "provisioning/ansible/db_server.yml"
