---
machines:
  ok_web:
    hostname: "ok_web"
    ipv4: "192.168.67.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/oakam-cms/"
      owner: www-data
      group: www-data
    port_map:
    - guest: 80
      host: 8080
    - guest: 443
      host: 4443

  ok_db:
    hostname: "ok_db"
    ipv4: "192.168.67.20"
    playbook: "provisioning/ansible/db_server.yml"
